### PR TITLE
Update a new UI && scene lora training and infer.

### PR DESCRIPTION
**Pull request by bubbliiiing**
1. New UI in Photo Infer.

image
image

2. Train scene Lora
image
image

### CODE REVIEW

**Comment by Fillllllllllll** [comment]
Hey! I have a problem with installing EasyPhoto, i'm using cagliostro-colab, and after installing extension and restarting - there is no EasyPhoto tab. May you help, please?

**Comment by wuziheng** [comment]
Bravo PR
1. A fantastic UI redesign that has clarified the functional division between T2I and I2I after integrating SCENE Lora
2. The inference and training of Scene LoRa have already been completed, and the results are excellent.

**Comment by wuziheng** [comment]
L1VzZXJzL3d6aC9MaWJyYXJ5L0NhY2hlcy9kZC53b3JrLmV4Y2x1c2l2ZTRhbGlkaW5nL3RodW1ibmFpbHMvOUJGNEYwMDEtNDgwNy00NjkzLUIyNzgtRkY5OThCRTQ0Q0RCLnBuZw==
download-1
download

分别是礼帽/果风/cyber-reddead2 三种风格！太棒了

**Review by wuziheng — COMMENTED** [review]
LGTM, merge after IPA

**Comment by wuziheng** [comment]
> Hey! I have a problem with installing EasyPhoto, i'm using cagliostro-colab, and after installing extension and restarting - there is no EasyPhoto tab. May you help, please?

please discuss in ISSUE, try to use lanrui-ai or Aliyun DSW, we dont support colab for now

**Comment by wuziheng** [comment]
test pass with main-IPA feature， good

**Comment by wuziheng** [comment]
image
截屏2023-11-21 上午10 59 19

**Comment by bubbliiiing** [comment]
image
infer api test

**Comment by bubbliiiing** [comment]
image
train api test

**Review by wuziheng — APPROVED** [review]
LGTM and tested

**Pull request merged**
